#! /usr/bin/bash


#clear

disk_usage() {
 
    echo "Usage: $0 [-d] [-n <number>] <directory>"
    echo ""
    echo " -d: List all files and directories within the specified directory"
    echo " -n <number>: Return the top N entries"
    exit 1

}



if [ "$#" -lt 1 ];
then
    disk_usage
fi

list_all=false
top_entries=0

while getopts ":dn:" opt; do
    case ${opt} in 
        d)
            list_all=true
             ;;
	n)
	    top_entries=$OPTARG
             ;;
        \?)
            echo "Error: Invalid option -$OPTARG" 1>&2
            disk_usage
            ;;
    esac
done

shift $((OPTIND -1))

if [ "$#" -lt 1 ]; then
    echo "Error: No directory specified"
    disk_usage
fi

directory="$1"

if [ ! -d "$directory" ]; then

    echo "Error: Directory '$directory' not found"

    exit 1

fi

echo "Disk usage of '$directory': "

if [ "$list_all" = true ]; then

    if [ "$top_entries" -eq 0 ]; then

        du_usage=$(du -h "$directory")

    
    elif [ ! "$list_all" ]; then
        du_usage=$(du -h "$directory" | head - 8)
  
    else

        du_usage=$(du -h "$directory" | head -n "$top_entries")

    fi

    echo "$du_usage"

else

    disk_usage_output=$(du -sh "$directory")

    echo "$disk_usage_output"

fi
